apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thai-erp.fullname" . }}
  labels:
    {{- include "thai-erp.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "thai-erp.databaseUrl" . | quote }}
  REDIS_URL: {{ include "thai-erp.redisUrl" . | quote }}
  NEXTAUTH_SECRET: {{ .Values.secrets.NEXTAUTH_SECRET | quote }}
  {{- range $key, $value := .Values.secrets }}
  {{- if and (ne $key "DATABASE_URL") (ne $key "REDIS_URL") (ne $key "NEXTAUTH_SECRET") }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
