apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: '2.40.0'
      cacheLevel: 'High'
      incrementalQuerying: true
      incrementalQueryOverlapWindow: 10m

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - name: 'TraceID'
          matcherRegex: 'trace_id=(\w+)'
          url: 'http://tempo:16686/trace/$${__value.raw}'
          urlDisplayLabel: 'View Trace'

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false

  - name: CloudWatch
    type: cloudwatch
    access: proxy
    editable: false
    jsonData:
      authType: default
      defaultRegion: ap-southeast-1
